### ISSUE TITLE
[Lava Generator] fill meter is "L" shaped

### ISSUE THREAD

**Issue by Yeehawlerz101** [TheMCBrothers/Useful-Machinery#3]
Heres a screenshot of all mods I'm using:
[https://ibb.co/W22pv3q](https://ibb.co/W22pv3q)
And here's what I see when I place lava manually in the lava generator.
[https://ibb.co/y0c3X5H](https://ibb.co/y0c3X5H)
Currently on MC 1.18.1
Forge V.39.0.0

**Comment by TheMCCrazyMan** [comment]
Hey thanks for your report,
It will be fixed in the next update
