### ISSUE TITLE
[Compactor Kit] Missing Texture In Game and in JEI

### ISSUE THREAD

**Issue by Yeehawlerz101** [TheMCBrothers/Useful-Machinery#4]
Heres a screenshot of all mods I'm using:
[https://ibb.co/W22pv3q](https://ibb.co/W22pv3q)
Howdy again! Found another Lil bug where the compactor kit is missing its textures.
[https://ibb.co/fSy28gm](https://ibb.co/fSy28gm)
Currently on MC 1.18.1
Forge V.39.0.0

**Comment by TheMCLoveMan** [comment]
Hi, thanks for reporting!
Try installing the [Useful Foundation](https://www.curseforge.com/minecraft/mc-mods/useful-foundation) mod (this should be required, our fault)
